import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    subsets: ["greek"],
    weight: "400",
});

export const metadata: Metadata = {
    title: {
        template: "%s | Campus Sync",
        default: "Campus Sync",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}