import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
    subsets: ["vietnamese"],
    weight: "400",
});

export const metadata: Metadata = {
    title: {
        template: "%s | Campus Sync",
        default: "Campus Sync",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} antialiased`}
            >
                <NextTopLoader
                    color="#000fff"
                    showSpinner={false}
                />
                <ClerkProvider
                    appearance={{
                        layout: {
                            animations: true,
                            showOptionalFields: true,
                            logoPlacement: "inside",
                            socialButtonsPlacement: "bottom",
                            socialButtonsVariant: "blockButton",
                            logoLinkUrl: "/",
                            termsPageUrl: "/terms",
                            privacyPageUrl: "/privacy",
                        },
                        variables: {
                            colorPrimary: "#6366f1"
                        },
                    }}
                >
                    <Toaster
                    />
                    {children}
                </ClerkProvider>
            </body>
        </html>
    );
}